### ISSUE TITLE
Autogenerated path

### ISSUE THREAD

**Issue by SendiMyrkr** [jiripudil/intellij-nette-tester#26]
I don't think that it's a good idea to generate path by used namespace. I think that shoud be better to generate it by structure where is tested class actually placed. I have three possible sollution which i think are more universal:

1) plugin will not generate path at all, you just insert file into folder where you create it.
2) plugin will have settings with application root and generete structure by folders under it by actually file place
3) plugin will generate path by structure from project root by actually file place

My opinion is that 1) is best, 3) as second best and then combination of 1) and 2) when 2) is used only in situation you create file at root of tests.

**Comment by jiripudil** [comment]
Could you elaborate more on your use case? Do you create the test directly as a new file, or do you use the `Navigate > Test > Create New Test` action on the intended class to test?

The generated path seemed super-useful to me in the latter use case: It follows the namespace mapping (set under Nette Tester in project settings) and, in turn, project source/test source roots settings so that if you follow some conventions (I'm mainly talking about PSR-0/PSR-4 here), you just have to hit Enter and the test is created in the right place. I love this feature and wouldn't fancy getting rid of it :/

If you create the test directly though, it might suffice to open the dialog in a different mode so that it wouldn't change the directory, what do you think?

**Comment by SendiMyrkr** [comment]
I do create new test by navigate ```New > Nette Tester > Nette Tester TestCase``` When i create it trough ```Navigate > Test > Create New Test``` so is created in same folder as original class, if that way should create file by his actual structure but in test folder that would be great.

"if you follow some conventions" That is the point, i do not. I agree it's super usefull in situation you strictily follow this standarts, but it's super annoing when you do not.

Possibility to open dialog in different mode should be good enough. Or some configuration like "Do not use PSR" or something like that.

**Comment by jiripudil** [comment]
> Possibility to open dialog in different mode should be good enough 

Well, then. I guess it's pretty safe to assume that you know where you want to put the test if you create it in the context of a specific directory :) I'll see what can be done about it.

---

Just to clarify, if you create the test through the `Navigate` action, it

1. determines the test namespace, based on the namespace mapping configured in the project settings. If you configure `Foo > Foo\Tests`, then a test for `Foo\Bar\Baz` maps to `Foo\Tests\Bar\Baz`. If you don't configure any mapping, the test is assumed to reside in the same namespace as the tested class (which is the standard with PHPUnit btw). This brings at least a bit of configurability into the enforced conventions.
2. determines the directory for the namespace, based on the `Directories` settings of source roots and their namespace prefixes. Test roots are preferred over source roots if they share the same prefix.

I know this is rather badly documented, which is something I'd like to improve before final 2.0.0 release.

**Comment by SendiMyrkr** [comment]
Oh, i didn't know that. That's nifty. But I personaly prefer subdirectory structure by source structure from ```Source``` over namespace. If that different dialog mode will have this behavior i'll be happy little developer :)
