### ISSUE TITLE
Fatal error: Undefined class constant 'SKIPPED'

### ISSUE THREAD

**Issue by krekos** [jiripudil/intellij-nette-tester#30]
I Just update Nette tester and this Error just shown up.
These constats was removed from Nette tester Runner class. 

Full Error Message:

Fatal error: Undefined class constant 'SKIPPED' in C:\Users\User\.PhpStorm2017.1\config\plugins\intellij-nette-tester\setup.php on line 39

Process finished with exit code 255

**Comment by jiripudil** [comment]
Currently only 1.x stable releases of Nette Tester are officially supported because, as you can see, dev-master can bring in breaking changes. Do you have a reason not to stay on a stable release?

The thing is, the upcoming Tester release (supposedly 2.0) will probably require a different setup script altogether, so I'm now hesitant to change the current one only to revert it some time later once Tester 2.0 is released and the plugin starts to support it 😕

**Comment by krekos** [comment]
Oh i see.
I don't have a specific reason to leave stable release. But i just like new things. And when i saw Nette Tester at verison 2 and your Plugin on version 2 as well, I thought that they are compatible. It's my bad and thank you for explanation.

**Comment by jiripudil** [comment]
The plugin actually already supports `-C` option (`Use system php.ini` setting) that's part of Tester's dev-master, but as I've discussed above, the situation with setup script is more complicated.

I'm not going to close this issue though. Tester 2.0 release date is somewhat unclear since it's maintainer @milo [has a baby](https://twitter.com/MiloNemilo/status/798432365681016832), so I might eventually fix this to support dev-master
