### ISSUE TITLE
Autocompletion of @testCase annotation is too strict

### ISSUE THREAD

**Issue by trebi** [jiripudil/intellij-nette-tester#35]
Tester plugin requires `@testCase` annotation to appear directly above class, but in order to be processed by  Nette\Tester, it could appear anywhere above. The check is unnecessary strict. 
```php
<?php
/**
 * @TestCase
 */

namespace ...;

use ...;

// Plugin wrongly assumes that @testCase annotation is missing and offers to complete it
final class MyTest extends \Tester\TestCase {
    // ...
}
```
Affected version: 2.0.0-beta.3

**Comment by mesour** [comment]
I tried to find a way to see if there was an annotation in the @testCase file, but I did. I fixed it in https://github.com/jiripudil/intellij-nette-tester/pull/46 but I only change highlighting the whole class to highlight only class name. I think we can close this issue, because if you use testCase in whole file, you can disable this inspection.
